{% set name = "executorlib-core" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/executorlib_core-{{ version }}.tar.gz
  sha256: 595102d45ea77718e2234f51f9d8ab0e8c8d3b713fa2cfed12b379cdbd84c9bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - cloudpickle
    - tqdm
    - pyzmq
    - versioneer
    - toml
  run:
    - cloudpickle >=2.0.0,<=3.0.0
    - python >=3.9
    - tqdm >=4.44.0,<=4.66.2
    - pyzmq >=25.0.0,<=26.0.2

test:
  imports:
    - executorlib_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/executorlib/executorlib-core
  summary: Library to develop your own concurrent.futures.Executor classes.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
